name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Vérifiez le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Installez Flutter
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.0'  # Spécifiez une version Flutter valide
          channel: stable

      # Obtenez les dépendances
      - name: Flutter Pub Get
        run: flutter pub get

      # Construisez et testez
      - name: Build and Test
        run: flutter test
