name: Flutter CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupération du code source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installation de Flutter (précisez la version et le canal)
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.5.0'  # Spécifiez la version exacte
          channel: stable           # Canal stable

      # 3. Vérification de la version Flutter installée
      - name: Flutter Version
        run: flutter --version

      # 4. Installation des dépendances
      - name: Flutter Pub Get
        run: flutter pub get

      # 5. Exécutez vos tests ou commandes
      - name: Run Flutter Tests
        run: flutter test
